In [1]:
%load_ext autoreload
%autoreload 2

In [12]:
from utils.figures_utils import *

In [3]:
load_sample("SRR26107673")

         CpG_chrm  CpG_start   CpG_end  methylated_reads  coverage
0            chr1      10468     10470                 0         0
1            chr1      10470     10472                 0         0
2            chr1      10483     10485                 0         0
3            chr1      10488     10490                 0         0
4            chr1      10492     10494                 0         0
...           ...        ...       ...               ...       ...
28217004     chrY   59362432  59362434                 0         0
28217005     chrY   59362484  59362486                 0         0
28217006     chrY   59362487  59362489                 0         0
28217007     chrY   59362492  59362494                 0         0
28217008     chrY   59362590  59362592                 0         0

[28217009 rows x 5 columns]

In [11]:
load_pmds("SRR26107673", "dnmtools")

     chrom      start        end
0     chr1    2682000    2990996
1     chr1    3995533    5918153
2     chr1    6991646    7276639
3     chr1   11388270   11716115
4     chr1   12673314   13051724
...    ...        ...        ...
1355  chrX  148710096  148908000
1356  chrX  150248678  150568936
1357  chrX  150628504  151058149
1358  chrX  151404027  152002900
1359  chrX  152463340  152602870

[1360 rows x 3 columns]

In [15]:
get_region_context_df()

,sample_id,tool,platform,region_type,chrom,start,end,region_length_bp,n_cpg,mean_meth,median_meth,meth_std,n_low_cpg,n_intermediate_cpg,n_high_cpg,pct_low,pct_intermediate,pct_high
0,ESO26.wgbs,methylseekr,wgbs,PMD,chr1,870240,937949,67709,180,0.498575,0.500000,0.339233,48,67,65,26.666667,37.222222,36.111111
1,ESO26.wgbs,methylseekr,wgbs,PMD,chr1,1420461,1427828,7367,59,0.837281,0.900000,0.189148,1,8,50,1.694915,13.559322,84.745763
2,ESO26.wgbs,methylseekr,wgbs,PMD,chr1,1443712,1458353,14641,106,0.741666,0.809091,0.241973,4,31,71,3.773585,29.245283,66.981132
3,ESO26.wgbs,methylseekr,wgbs,PMD,chr1,1580026,1592892,12866,113,0.574914,0.625000,0.331185,17,45,51,15.044248,39.823009,45.132743
4,ESO26.wgbs,methylseekr,wgbs,PMD,chr1,1600032,1612775,12743,64,0.682856,0.769737,0.283420,4,24,36,6.250000,37.500000,56.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1287189,WGBS_colon-primary-tumor_3_meth,mmseekr,wgbs,PMD,chr9,136329868,136357897,28029,953,0.492925,0.466667,0.227606,81,687,185,8.499475,72.088143,19.412382
1287190,WGBS_colon-primary-tumor_3_meth,mmseekr,wgbs,PMD,chr9,136603836,136641047,37211,940,0.562737,0.571429,0.264479,95,511,334,10.106383,54.361702,35.531915
1287191,WGBS_colon-primary-tumor_3_meth,mmseekr,wgbs,PMD,chr9,137857744,138147816,290072,4217,0.641743,0.677419,0.253117,198,2050,1969,4.695281,48.612758,46.691961
1287192,WGBS_colon-primary-tumor_3_meth,mmseekr,wgbs,PMD,chr9,138189266,138222000,32734,260,0.652702,0.707780,0.257376,12,117,131,4.615385,45.000000,50.384615
1287193,WGBS_colon-primary-tumor_3_meth,mmseekr,wgbs,PMD,chr9,138394700,138394717,17,0,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN